version: "3.1"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: "swipe"
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - HOST=0.0.0.0
    networks:
      - swipe_bridge
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - swipe_bridge
    command: "swipe --start=worker"
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - swipe_bridge
    command: /bin/sh -c "redis-server --requirepass password"
    environment:
      - REDIS_HOST_PASSWORD=password
    volumes:
      - ./.swipe/redis:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: swipe
      POSTGRES_PASSWORD: swip3@admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    restart: on-failure:3
    networks:
      - swipe_bridge
    volumes:
      - ./.swipe/postgres:/var/lib/postgresql/data
networks:
  swipe_bridge:
volumes:
  boot:
