basePath: /
definitions:
  dtos.CardArticle:
    properties:
      category:
        type: string
      content:
        items:
          $ref: '#/definitions/dtos.CardContent'
        type: array
      src:
        type: string
      title:
        type: string
    required:
    - category
    - title
    type: object
  dtos.CardContent:
    properties:
      content:
        type: string
      src:
        type: string
    required:
    - content
    type: object
  dtos.CollectionUpload:
    properties:
      id:
        type: integer
      msg:
        type: string
    type: object
  dtos.Comment:
    properties:
      content:
        items:
          type: string
        type: array
      dislike:
        type: integer
      id:
        description: Position string   `json:"position" validate:"required"`
        type: integer
      level:
        description: '0: parent, 1: child'
        type: integer
      like:
        type: integer
      parent_id:
        type: integer
      product_id:
        type: integer
      rating:
        type: integer
      user_id:
        type: integer
      username:
        type: string
    required:
    - content
    - dislike
    - id
    - level
    - like
    - rating
    - username
    type: object
  dtos.News:
    properties:
      cards:
        items:
          $ref: '#/definitions/dtos.CardArticle'
        type: array
      header:
        type: string
    required:
    - cards
    - header
    type: object
  dtos.NewsDTO:
    properties:
      cards:
        items:
          $ref: '#/definitions/dtos.CardArticle'
        type: array
      category:
        type: string
      header:
        type: string
    required:
    - cards
    - category
    - header
    type: object
  dtos.OK:
    properties:
      msg:
        type: string
    type: object
info:
  contact: {}
  description: This is a documentation for the Swipe API
  title: Swipe Public API v0.0.1
  version: 0.0.1
paths:
  /comment:
    get:
      consumes:
      - application/json
      description: get all comments of product
      parameters:
      - description: id of products
        in: query
        name: product_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.Comment'
      tags:
      - comments
    post:
      consumes:
      - application/json
      description: create comment into products
      parameters:
      - description: comment data request
        in: body
        name: banner
        required: true
        schema:
          $ref: '#/definitions/dtos.Comment'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.OK'
      tags:
      - comment
  /news:
    get:
      consumes:
      - application/json
      description: get news
      parameters:
      - description: category of news
        in: query
        name: category
        required: true
        type: string
      - description: limit of cards carousel
        in: query
        name: limit
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.News'
      tags:
      - news
    post:
      consumes:
      - application/json
      description: create news
      parameters:
      - description: news Request
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/dtos.NewsDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.CollectionUpload'
      tags:
      - news
  /news/image:
    put:
      consumes:
      - application/json
      description: update news image
      parameters:
      - description: image of news
        in: formData
        name: img
        required: true
        type: file
      - description: news identifier
        in: formData
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.OK'
      tags:
      - news
swagger: "2.0"
