name: build test products module

on:
  push:
    branches:
      - stag/products
  pull_request:

jobs:
  build:
    name: build products module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build the Go application
        run: sh hack/ci/products.sh

      - name: Remove binaries
        run: rm -rf bin

  test-products:
    needs: [build]
    name: unit test products module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Unit test - products
        run: go test -v ./testing/products
